Repository aniketbhoite/Assume, pull requests merged in 2021-05, with the labels that each got.

#3 first readme version
  README.md
Labels: documentation

#5 Add feature to ignore assume response and get actual API response.
  annotations-empty/src/main/java/com/aniketbhoite/assume/annotations/Annotation.kt
  annotations/src/main/java/com/aniketbhoite/assume/annotations/Annotation.kt
  app/src/main/java/com/aniketbhoite/assume/ApiService.kt
  app/src/main/java/com/aniketbhoite/assume/MainActivity.kt
  processor/src/main/java/com/aniketbhoite/assume/processor/AssumeProcessor.kt
Labels: enhancement

#6 add spotless
  .idea/codeStyles/Project.xml
  annotations-empty/src/main/java/com/aniketbhoite/assume/annotations/Annotation.kt
  annotations-empty/src/main/java/com/aniketbhoite/assume/interceptor/AssumeInterceptor.kt
  annotations/src/main/java/com/aniketbhoite/assume/annotations/Annotation.kt
  annotations/src/main/java/com/aniketbhoite/assume/interceptor/AssumeInterceptor.kt
  annotations/src/main/java/com/aniketbhoite/assume/interceptor/AssumeInterceptorHelper.kt
  app/src/androidTest/java/com/aniketbhoite/assume/ExampleInstrumentedTest.kt
  app/src/main/java/com/aniketbhoite/assume/ApiService.kt
  app/src/main/java/com/aniketbhoite/assume/MainActivity.kt
  app/src/test/java/com/aniketbhoite/assume/ExampleUnitTest.kt
  build.gradle
  processor/src/main/java/com/aniketbhoite/assume/processor/AssumeProcessor.kt
  processor/src/main/java/com/aniketbhoite/assume/processor/KotlinProcessingEnvironment.kt
  processor/src/main/java/com/aniketbhoite/assume/processor/ProcessorUtil.kt
  processor/src/test/kotlin/com/aniketbhoite/assume/AssumeProcessorTest.kt
Labels: Spotless-applied, enhancement

#7 use default mediaType in response
  annotations/src/main/java/com/aniketbhoite/assume/interceptor/AssumeInterceptor.kt
  app/src/main/java/com/aniketbhoite/assume/ApiService.kt
Labels: Spotless-applied, bug

#8 Add JsonPlaceHolder API.
  .gitignore
  app/build.gradle
  app/src/main/java/com/aniketbhoite/assume/ApiService.kt
  app/src/main/java/com/aniketbhoite/assume/MainActivity.kt
  app/src/main/java/com/aniketbhoite/assume/NewsResponse.kt
  app/src/main/java/com/aniketbhoite/assume/data/CommentModel.kt
  app/src/main/java/com/aniketbhoite/assume/data/PostListModelItem.kt
  app/src/main/java/com/aniketbhoite/assume/di/DI.kt
  app/src/main/java/com/aniketbhoite/assume/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: Spotless-applied, enhancement
